### ISSUE TITLE
"No such file or directory" error for file that exists

### ISSUE THREAD

**Issue by daisybelle36** [daisybelle36/projects#2]
```
(venv) tania@Tanias-MacBook-Pro:~/github/projects/whisper/test$ ../transcribe_file.py test_file_01.m4a
args=Namespace(audio_file='test_file_01.m4a')
prefix='test_file_01'
audio_input='test_file_01.m4a'
/Users/tania/github/projects/whisper/venv/lib/python3.11/site-packages/whisper/transcribe.py:114: UserWarning: FP16 is not supported on CPU; using FP32 instead
  warnings.warn("FP16 is not supported on CPU; using FP32 instead")
Traceback (most recent call last):
  File "/Users/tania/github/projects/whisper/venv/lib/python3.11/site-packages/whisper/audio.py", line 59, in load_audio
    out = run(cmd, capture_output=True, check=True).stdout
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tania/.pyenv/versions/3.11.4/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ffmpeg', '-nostdin', '-threads', '0', '-i', 'audio_input', '-f', 's16le', '-ac', '1', '-acodec', 'pcm_s16le', '-ar', '16000', '-']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/tania/github/projects/whisper/test/../transcribe_file.py", line 52, in <module>
    main()
  File "/Users/tania/github/projects/whisper/test/../transcribe_file.py", line 42, in main
    result = model.transcribe("audio_input")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tania/github/projects/whisper/venv/lib/python3.11/site-packages/whisper/transcribe.py", line 121, in transcribe
    mel = log_mel_spectrogram(audio, padding=N_SAMPLES)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tania/github/projects/whisper/venv/lib/python3.11/site-packages/whisper/audio.py", line 140, in log_mel_spectrogram
    audio = load_audio(audio)
            ^^^^^^^^^^^^^^^^^
  File "/Users/tania/github/projects/whisper/venv/lib/python3.11/site-packages/whisper/audio.py", line 61, in load_audio
    raise RuntimeError(f"Failed to load audio: {e.stderr.decode()}") from e
RuntimeError: Failed to load audio: ffmpeg version 6.0 Copyright (c) 2000-2023 the FFmpeg developers
  built with Apple clang version 14.0.3 (clang-1403.0.22.14.1)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/6.0 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
audio_input: No such file or directory
```

**Comment by daisybelle36** [comment]
This error appears to be caused by this warning:

```
/Users/tania/github/projects/whisper/venv/lib/python3.11/site-packages/whisper/transcribe.py:114: UserWarning: FP16 is not supported on CPU; using FP32 instead
  warnings.warn("FP16 is not supported on CPU; using FP32 instead")
```

Fix this by modifying 
`	result = model.transcribe(args.audio_file)`
to add the `fp` info in the original call:
`	result = model.transcribe(args.audio_file, fp16=False)`

**Comment by daisybelle36** [comment]
Commit made: 74de2d0
